version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
      - docker build -t demo .
      - docker tag demo public.ecr.aws/f9s4g9c5/tarosuke777/demo
  post_build:
    commands:
       - docker push public.ecr.aws/f9s4g9c5/tarosuke777/demo
       - echo "[{\"name\":\"ecs-hms-task\",\"imageUri\":\"public.ecr.aws/f9s4g9c5/tarosuke777/demo:latest\"}]" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json